"""
make_synthetic_eo.py -- the D0 replay harness. Indoor demo, no water.

WHY THIS FILE EXISTS
04_demo/DEMO_INDOOR.md: there is no water access, so no camera can observe a vessel.
Every module downstream of the camera (association, consistency, verdict, prioritizer,
evidence) is a pure function of EoContact + AisTrack, so none of them need to change.
Only the PRODUCER of EoContact changes. This is that producer.

WHAT IT DOES
Takes the real pseudonymised DMA golden window, treats each vessel's real AIS record as
GROUND TRUTH ABOUT THE PHYSICAL HULL, and answers: "if a camera had stood at this pose,
what would it have seen?" Then it deliberately breaks some of the claims, so there is
something to find.

THE SEMANTICS THAT MAKE THIS HONEST, AND NOT CIRCULAR
    truth        = the real AIS record. The physical vessel.
    observation  = truth, projected through the camera, PLUS measurement error.
    claim        = truth, sometimes MUTATED (that mutation is the lie) or DELETED.

A spoofer is generated by changing the CLAIM and leaving the OBSERVATION at truth --
which is exactly what a real spoofer does. It lies about what it is, not about where it
is, so it still associates perfectly and can only be caught by comparing content.

THE THING THAT WOULD MAKE THIS WORTHLESS, AND HOW IT IS AVOIDED
If observations were a perfect projection of the claims, every association would score
at zero sigma, every tolerance would pass, and the demo would prove nothing except that
a == a. Worse, it would hide real defects in association.py until the judges found them.
So MEASUREMENT ERROR IS MANDATORY here, not optional: bearing noise from the pose,
fractional range error because monocular range is genuinely bad, length error, class
confusion between visually similar types, missed detections, and clutter contacts that
belong to nothing. Set --noise none only to debug the plumbing, never for a demo.

GROUND TRUTH IS WRITTEN TO A SEPARATE FILE, DELIBERATELY
No field on EoContact or AisTrack records that a vessel was tampered with. If the answer
key travelled inside the data, a downstream lane could read it by accident and score
100%, and nobody would notice until the demo. ground_truth.jsonl is the answer key and
nothing in 03_src may import it.

WHAT THIS FILE MUST NEVER DO
Import consistency.py, verdict.py or prioritizer.py. It produces INPUTS. If it ever
learns what a verdict is, it can be tuned -- consciously or not -- to produce the
verdicts we want, and the measured false-positive rate becomes a fiction.

USAGE
    python 04_demo/make_synthetic_eo.py \
        --ais 02_data/golden/fehmarn_2026-08-25_1000-1100_anon.csv \
        --out 04_demo/out/scene01 \
        --scene-time 2026-08-25T10:30:00+00:00 \
        --seed 20260830

    python 04_demo/make_synthetic_eo.py --ais <csv> --out <dir> --dry-run
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Iterable

import numpy as np
from pyproj import Geod

# 03_src has a leading digit and is not a legal package name -- tests/conftest.py
# settles this project-wide with sys.path + flat imports. Same convention here.
_SRC = Path(__file__).resolve().parents[1] / "03_src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from ais_ingest import DmaCsvSource                      # noqa: E402
from association import predict_measurement, is_in_field_of_view  # noqa: E402
from contracts import AisTrack, EoContact                # noqa: E402

HARNESS_VERSION = "make_synthetic_eo/0.1.0"
GEOD = Geod(ellps="WGS84")
KN_TO_MS = 0.514444


# ============================================================================
# Geometry helpers.
#
# These duplicate two small functions from eo_detector.py. They are imported from
# there when it imports cleanly, and only re-implemented when it does not -- that
# module pulls in cv2 and ultralytics at import time, which are heavy and, on a
# machine without them, would make this harness unrunnable for no reason.
#
# The fallback formulas are byte-identical to lane B's. If lane B changes the
# bearing model, THIS FALLBACK IS A DIVERGENCE RISK -- it belongs in geometry.py,
# which is still empty. Filed to lane B.
# ============================================================================

# Lane B delivered geometry.py while this harness was being written, and it now owns
# the bearing model that eo_detector.py used to hold. Import from there.
#
# WHY THE FALLBACK STILL EXISTS: if geometry.py cannot be imported (a missing pyproj on
# a stripped machine), a SILENT fallback to a local copy is the dangerous outcome -- the
# harness would keep running and produce bearings from a second, possibly divergent,
# implementation. So the fallback announces itself, and _GEOM_SOURCE is written into the
# scene manifest so any run built on it is identifiable after the fact.

try:
    from geometry import (                                   # noqa: E402
        bearing_uncertainty_deg,
        focal_length_px,
        signed_delta_deg as _signed_delta_deg,
    )
    _GEOM_SOURCE = "geometry"
except Exception as _exc:  # pragma: no cover
    import warnings
    warnings.warn(
        f"geometry.py unavailable ({type(_exc).__name__}: {_exc}). Falling back to a "
        f"LOCAL copy of the bearing model. Bearings from this run come from a second "
        f"implementation and must not be compared against a run that used geometry.py.",
        stacklevel=2)
    _GEOM_SOURCE = "local_fallback"

    def focal_length_px(image_width_px: int, hfov_deg: float) -> float:
        return (image_width_px / 2.0) / math.tan(math.radians(hfov_deg) / 2.0)

    def bearing_uncertainty_deg(
        bbox_width_px: float,
        centre_x_px: float,
        image_width_px: int,
        hfov_deg: float,
        yaw_uncertainty_deg: float,
    ) -> float:
        f = focal_length_px(image_width_px, hfov_deg)
        centroid_px = max(bbox_width_px * 0.10, 1.0)
        d_deg_d_px = math.degrees(f / (f * f + (centre_x_px - image_width_px / 2.0) ** 2))
        return math.sqrt(yaw_uncertainty_deg ** 2 + (centroid_px * d_deg_d_px) ** 2)

    def _signed_delta_deg(a: float, b: float) -> float:
        return (a - b + 180.0) % 360.0 - 180.0


def pixel_column_for_relative_bearing(
    rel_deg: float, image_width_px: int, hfov_deg: float
) -> float:
    """
    Inverse of eo_detector.relative_bearing_deg.

    WHY THE INVERSE AND NOT A LINEAR MAP: lane B uses atan2 because a rectilinear lens
    does not put angle linearly onto pixels. If this harness placed boxes linearly, then
    every synthetic contact near a frame edge would carry a bearing several degrees away
    from where the real detector would have put it -- and several degrees is larger than
    the mismatches we are trying to detect. The synthetic frame has to obey the same
    optics as the real one or the demo is measuring the harness, not the pipeline.
    """
    f = focal_length_px(image_width_px, hfov_deg)
    return image_width_px / 2.0 + f * math.tan(math.radians(rel_deg))


def shortest_arc_deg(a: float, b: float) -> float:
    """Signed shortest angular difference a - b in (-180, +180]. Delegates to lane B."""
    return _signed_delta_deg(a, b)


def wrap_360(deg: float) -> float:
    return deg % 360.0


# ============================================================================
# Scene configuration.
# ============================================================================

@dataclass(frozen=True)
class ScenePose:
    """
    The synthetic camera. Frozen for the same reason CameraPose is frozen in
    eo_detector.py: a pose that can change after the frames were produced is not
    evidence, and every bearing in the run inherits its uncertainty.
    """

    pose_ref: str
    lat_deg: float
    lon_deg: float
    boresight_deg_true: float
    hfov_deg: float
    yaw_uncertainty_deg: float
    max_range_m: float
    image_width_px: int
    image_height_px: int
    height_m: float

    @property
    def fov_half_angle_deg(self) -> float:
        return self.hfov_deg / 2.0

    def to_dict(self) -> dict[str, Any]:
        d = {k: getattr(self, k) for k in self.__dataclass_fields__}
        d["fov_half_angle_deg"] = self.fov_half_angle_deg
        return d


@dataclass(frozen=True)
class NoiseModel:
    """
    Measurement error. Every number here is a defensible guess, NOT a measurement,
    and the manifest says so. They are set to be pessimistic rather than flattering:
    an optimistic noise model produces a demo that works and a system that does not.
    """

    bearing_centroid_sigma_deg: float = 0.35
    range_fraction_sigma: float = 0.25   # monocular range is bad. 25% 1-sigma is kind.
    length_fraction_sigma: float = 0.15
    heading_sigma_deg: float = 12.0
    speed_fraction_sigma: float = 0.20
    p_missed_detection: float = 0.06
    p_class_confusion: float = 0.18
    n_clutter_contacts: int = 2
    class_confidence_lo: float = 0.45
    class_confidence_hi: float = 0.92

    @classmethod
    def off(cls) -> "NoiseModel":
        return cls(
            bearing_centroid_sigma_deg=0.0, range_fraction_sigma=0.0,
            length_fraction_sigma=0.0, heading_sigma_deg=0.0,
            speed_fraction_sigma=0.0, p_missed_detection=0.0,
            p_class_confusion=0.0, n_clutter_contacts=0,
            class_confidence_lo=0.99, class_confidence_hi=0.99,
        )


# Visually confusable pairs. A VLM does not confuse a tanker with a fishing boat at
# 4 km; it confuses a tanker with a cargo ship, because from the beam they are two
# boxes with a superstructure aft. Random class noise would be dishonest in the other
# direction -- it would manufacture easy "spoofs" that a real system would never see.
CLASS_CONFUSION: dict[str, list[str]] = {
    "cargo": ["tanker"],
    "tanker": ["cargo"],
    "tug": ["small_craft", "fishing"],
    "fishing": ["small_craft", "tug"],
    "small_craft": ["fishing"],
    "passenger": ["cargo"],
    "naval": ["cargo", "tug"],
}


# ============================================================================
# Fault injection.
# ============================================================================

FAULT_KINDS = (
    "dark",             # observation with no claim              -> expect DARK
    "length_spoof",     # claim inflates/deflates size           -> expect SPOOF/identity
    "class_spoof",      # claim asserts a different ship type    -> expect SPOOF/identity
    "position_spoof",   # claim displaced from the real hull     -> expect SPOOF/position
    "heading_spoof",    # claim points a different way           -> expect SPOOF/identity
    "coverage_hole",    # CONTROL: claim dropped OUTSIDE the FOV -> expect nothing
    "missed_detection", # CONTROL: hull in view, detector missed -> expect defer, not SPOOF
)


@dataclass
class Injection:
    """One deliberate fault, and everything needed to score the result later."""

    kind: str
    mmsi: str
    track_id: str | None = None
    contact_id: str | None = None
    detail: dict[str, Any] = field(default_factory=dict)
    expected_label: str = ""
    expected_spoof_subtype: str | None = None
    must_not_fire: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "kind": self.kind, "mmsi": self.mmsi, "track_id": self.track_id,
            "contact_id": self.contact_id, "detail": self.detail,
            "expected_label": self.expected_label,
            "expected_spoof_subtype": self.expected_spoof_subtype,
            "must_not_fire": self.must_not_fire,
        }


EXPECTATIONS = {
    "dark":             ("DARK", None, False),
    "length_spoof":     ("SPOOF", "identity", False),
    "class_spoof":      ("SPOOF", "identity", False),
    "position_spoof":   ("SPOOF", "position", False),
    "heading_spoof":    ("SPOOF", "identity", False),
    # The two controls. must_not_fire=True means: producing DARK or SPOOF here is a
    # FALSE POSITIVE, and the false-positive rate quoted on Sunday is measured off
    # exactly these rows. This is criterion 4 made numeric.
    "coverage_hole":    ("UNKNOWN", None, True),
    "missed_detection": ("UNKNOWN", None, True),
}


# ============================================================================
# Loading truth.
# ============================================================================

def load_truth_states(
    csv_path: Path, scene_time: datetime, window_s: float
) -> tuple[list[AisTrack], dict[str, Any]]:
    """
    One AisTrack per vessel: the report closest in time to scene_time.

    WHY NEAREST-IN-TIME AND NOT THE LATEST BEFORE: this is the TRUTH state of the hull,
    not what an operator would have had. Taking the nearest report minimises the
    dead-reckoning error baked into the scene, so any residual that association.py
    reports comes from the noise model and the injected faults -- things we chose --
    rather than from an arbitrary sampling lag we did not intend and cannot account for.
    """
    lo = scene_time - timedelta(seconds=window_s)
    hi = scene_time + timedelta(seconds=window_s)
    source = DmaCsvSource(csv_path, start_utc=lo, end_utc=hi)

    best: dict[str, tuple[float, AisTrack]] = {}
    n_read = 0
    for track in source.tracks():
        n_read += 1
        dt = abs((track.report_time_utc - scene_time).total_seconds())
        prev = best.get(track.claimed_mmsi)
        if prev is None or dt < prev[0]:
            best[track.claimed_mmsi] = (dt, track)

    tracks = [t for _, t in sorted(best.values(), key=lambda p: p[1].claimed_mmsi)]
    stats = {
        "rows_considered": n_read,
        "vessels": len(tracks),
        "window_s": window_s,
        "scene_time_utc": scene_time.isoformat(),
    }
    return tracks, stats


def assert_pseudonymised(tracks: Iterable[AisTrack], *, allow_real: bool) -> None:
    """
    Refuse to build a scene from real identities unless explicitly forced.

    WHY THIS IS A HARD STOP AND NOT A WARNING: constraint 2 -- a demo that labels a real
    named vessel as a spoofer is defamatory and indefensible, and the DMA licence
    separately forbids combining this data with others to identify individuals. The
    golden-window pseudonymiser puts every synthetic MMSI on the 999 prefix, which is a
    MID unassigned to any country, so it is recognisably fake to anyone who checks.
    A run that finds non-999 MMSIs is reading the wrong file -- almost certainly the
    *_real* one sitting next to it -- and that is exactly the mistake worth stopping.
    """
    real = sorted({t.claimed_mmsi for t in tracks if not t.claimed_mmsi.startswith("999")})
    if not real:
        return
    msg = (
        f"{len(real)} of the loaded MMSIs are not 999-prefixed, i.e. they are REAL "
        f"vessel identities (first few: {real[:5]}). Point --ais at the *_anon.csv "
        f"produced by 02_data/make_golden_window.py."
    )
    if not allow_real:
        raise SystemExit("REFUSING TO BUILD SCENE: " + msg)
    print("WARNING -- --allow-real-identities was passed. " + msg, file=sys.stderr)
    print("WARNING -- output of this run must NEVER be committed or shown publicly.",
          file=sys.stderr)


# ============================================================================
# Pose selection.
# ============================================================================

def auto_pose(tracks: list[AisTrack], *, max_range_m: float, hfov_deg: float,
              yaw_uncertainty_deg: float, image_width_px: int,
              image_height_px: int) -> ScenePose:
    """
    Put the camera where it sees the most traffic.

    Method: take the median vessel position as the scene centre, step back
    max_range_m * 0.8 from it along the axis of least traffic spread (so the camera
    looks ACROSS the shipping lane rather than down it -- a camera looking down a lane
    sees a queue of overlapping hulls, which is the worst case for association and a
    terrible thing to demo), and aim the boresight at the median.
    """
    lats = np.array([t.claimed_lat_deg for t in tracks])
    lons = np.array([t.claimed_lon_deg for t in tracks])
    c_lat, c_lon = float(np.median(lats)), float(np.median(lons))

    # Principal axis of the traffic, via the covariance of local metric offsets.
    m_per_deg_lat = 111_320.0
    m_per_deg_lon = 111_320.0 * math.cos(math.radians(c_lat))
    x = (lons - c_lon) * m_per_deg_lon
    y = (lats - c_lat) * m_per_deg_lat
    if len(x) >= 2 and (x.std() > 0 or y.std() > 0):
        cov = np.cov(np.vstack([x, y]))
        vals, vecs = np.linalg.eigh(cov)
        major = vecs[:, int(np.argmax(vals))]
        lane_deg = wrap_360(math.degrees(math.atan2(major[0], major[1])))
    else:
        lane_deg = 0.0

    stand_off_az = wrap_360(lane_deg + 90.0)          # perpendicular to the lane
    stand_off_m = max_range_m * 0.8
    cam_lon, cam_lat, _ = GEOD.fwd(c_lon, c_lat, stand_off_az, stand_off_m)
    boresight, _, _ = GEOD.inv(cam_lon, cam_lat, c_lon, c_lat)

    return ScenePose(
        pose_ref=f"synthetic-auto-{wrap_360(boresight):06.2f}T",
        lat_deg=float(cam_lat), lon_deg=float(cam_lon),
        boresight_deg_true=wrap_360(float(boresight)),
        hfov_deg=hfov_deg, yaw_uncertainty_deg=yaw_uncertainty_deg,
        max_range_m=max_range_m, image_width_px=image_width_px,
        image_height_px=image_height_px, height_m=25.0,
    )


# ============================================================================
# Projection: truth -> what the camera would have seen.
# ============================================================================

def project(tracks: list[AisTrack], pose: ScenePose) -> dict[str, Any]:
    """Bearing, range and visibility for every vessel. No noise yet."""
    lat = np.array([t.claimed_lat_deg for t in tracks])
    lon = np.array([t.claimed_lon_deg for t in tracks])
    bearing, rng = predict_measurement(
        camera_lat_deg=pose.lat_deg, camera_lon_deg=pose.lon_deg,
        target_lat_deg=lat, target_lon_deg=lon,
    )
    visible = is_in_field_of_view(
        bearing, rng,
        boresight_deg_true=pose.boresight_deg_true,
        fov_half_angle_deg=pose.fov_half_angle_deg,
        max_range_m=pose.max_range_m,
    )
    return {"bearing": bearing, "range": rng, "visible": np.asarray(visible, dtype=bool)}


def _synthetic_detection_confidence(apparent_width_px: float, rng) -> float:
    """A plausible detector confidence for a synthetic contact.

    ONE RULE FOR REAL VESSELS AND FOR CLUTTER, deliberately. It would be easy to give
    injected clutter a systematically low confidence and real vessels a high one, and
    that would be cheating: any downstream use of detection_confidence would then
    separate the two trivially, and the false-positive rate measured on this scene
    would be optimistic in a way nothing in the output reveals.

    Instead confidence rises with APPARENT PIXEL WIDTH, which is the physical reason a
    real detector is more certain about a near contact than a far one. Clutter is small,
    so it lands low WITHOUT being labelled low, and a genuinely distant vessel lands in
    the same band as clutter -- which is exactly the ambiguity the pipeline has to earn
    its way out of.

    Saturating rather than linear: past a few hundred pixels a detector is as sure as it
    is going to get. Measured shape: 6 px -> 0.43, 22 px -> 0.58, 40 px -> 0.70,
    100 px -> 0.85, 200 px -> 0.90.
    """
    import math as _math
    base = 0.35 + 0.55 * (1.0 - _math.exp(-max(0.0, apparent_width_px) / 40.0))
    return float(min(0.98, max(0.25, base + rng.normal(0.0, 0.05))))


def make_contact(
    *, track: AisTrack, bearing_true: float, range_m: float, pose: ScenePose,
    scene_time: datetime, rng: np.random.Generator, noise: NoiseModel,
    contact_id: str, track_length_frames: int,
) -> EoContact:
    """
    Build one EoContact from one vessel's truth state, with measurement error applied.

    Note the ordering, which matters: geometry is perturbed FIRST, then the pixel box is
    computed from the perturbed bearing. Doing it the other way round -- perfect box,
    noisy bearing -- would produce a contact whose bbox and bearing disagree, and any
    downstream code that recomputes bearing from the box (a reasonable thing to do)
    would silently get a different answer than the one in the field.
    """
    # 1. Bearing error. Two independent sources, so they add in quadrature.
    #    Pose yaw error is SYSTEMATIC -- it rotates the whole scene by one amount -- but
    #    it is applied per-contact here for simplicity; the run manifest records that.
    b_sigma = math.sqrt(pose.yaw_uncertainty_deg ** 2 + noise.bearing_centroid_sigma_deg ** 2)
    obs_bearing = wrap_360(bearing_true + rng.normal(0.0, b_sigma))

    # 2. Range error is FRACTIONAL, not absolute. A monocular range estimate at 5 km is
    #    not 5000 +/- 200 m, it is 5000 +/- 1250 m, because the estimate divides by an
    #    apparent size that is itself only a few pixels. Modelling it as absolute error
    #    would make distant contacts look far more trustworthy than they are, and
    #    distant contacts are exactly the ones a patrol decision turns on.
    r_sigma = range_m * noise.range_fraction_sigma
    obs_range = max(1.0, range_m + rng.normal(0.0, r_sigma)) if r_sigma > 0 else range_m

    # 3. Pixel geometry, derived from the PERTURBED bearing.
    rel = shortest_arc_deg(obs_bearing, pose.boresight_deg_true)
    centre_x = pixel_column_for_relative_bearing(rel, pose.image_width_px, pose.hfov_deg)
    f_px = focal_length_px(pose.image_width_px, pose.hfov_deg)

    true_len = track.claimed_length_m or 30.0
    width_px = max(4.0, f_px * true_len / max(range_m, 1.0))
    height_px = max(3.0, width_px / 3.2)
    x0 = int(round(centre_x - width_px / 2.0))
    x1 = int(round(centre_x + width_px / 2.0))
    y_c = pose.image_height_px * 0.55
    y0 = int(round(y_c - height_px / 2.0))
    y1 = int(round(y_c + height_px / 2.0))
    x0, x1 = max(0, x0), min(pose.image_width_px, max(x0 + 1, x1))
    y0, y1 = max(0, y0), min(pose.image_height_px, max(y0 + 1, y1))

    b_unc = bearing_uncertainty_deg(
        float(x1 - x0), float(centre_x), pose.image_width_px, pose.hfov_deg,
        pose.yaw_uncertainty_deg,
    )

    # 4. Observed length. Truth times a fractional error -- the same reasoning as range,
    #    and in fact the two are coupled in reality (length is derived FROM range).
    #    Kept independent here, which is a simplification recorded in the manifest.
    obs_len = None
    obs_len_unc = None
    if track.claimed_length_m is not None:
        scale = 1.0 + rng.normal(0.0, noise.length_fraction_sigma)
        obs_len = max(1.0, track.claimed_length_m * max(0.2, scale))
        obs_len_unc = max(1.0, obs_len * noise.length_fraction_sigma)

    # 5. Observed class, with CONFUSION RESTRICTED TO VISUALLY SIMILAR TYPES.
    obs_class = track.claimed_ship_type
    if obs_class == "unknown":
        # Lane A's conservative policy: "unknown" means a claim was made that has no
        # honest silhouette equivalent. The camera still sees SOMETHING, so the observed
        # class is not None -- but it must never be compared. That suppression is
        # consistency.py's job; here we just record what was seen.
        obs_class = None
    if obs_class is not None and rng.random() < noise.p_class_confusion:
        alts = CLASS_CONFUSION.get(obs_class, [])
        if alts:
            obs_class = str(rng.choice(alts))
    obs_class_conf = (
        float(rng.uniform(noise.class_confidence_lo, noise.class_confidence_hi))
        if obs_class is not None else None
    )

    # 6. Motion. Only meaningful with a multi-frame track -- a single-frame contact
    #    cannot support a speed or heading observation, and contracts.py has a
    #    defer_reason (single_frame_contact) that exists precisely for this.
    obs_heading = None
    obs_speed = None
    if track_length_frames > 1:
        base_hdg = track.claimed_heading_deg_true
        if base_hdg is None:
            base_hdg = track.claimed_cog_deg_true
        if base_hdg is not None:
            obs_heading = wrap_360(base_hdg + rng.normal(0.0, noise.heading_sigma_deg))
        if track.claimed_sog_kn is not None:
            ms = track.claimed_sog_kn * KN_TO_MS
            obs_speed = max(0.0, ms * (1.0 + rng.normal(0.0, noise.speed_fraction_sigma)))

    return EoContact(
        contact_id=contact_id,
        frame_time_utc=scene_time,
        frame_ref=f"synthetic://{pose.pose_ref}/{scene_time.isoformat()}",
        bbox_px=(x0, y0, x1, y1),
        observed_bearing_deg_true=obs_bearing,
        bearing_uncertainty_deg=b_unc,
        detection_confidence=_synthetic_detection_confidence(width_px, rng),
        observed_bearing_rel_deg=max(-180.0, min(180.0, rel)),
        observed_range_m=obs_range,
        range_uncertainty_m=max(1.0, r_sigma) if r_sigma > 0 else 1.0,
        observed_class=obs_class,
        observed_class_confidence=obs_class_conf,
        observed_length_m=obs_len,
        observed_length_uncertainty_m=obs_len_unc,
        observed_heading_deg_true=obs_heading,
        observed_speed_ms=obs_speed,
        track_length_frames=track_length_frames,
        camera_pose_ref=pose.pose_ref,
    )


def make_clutter_contact(
    *, pose: ScenePose, scene_time: datetime, rng: np.random.Generator,
    noise: NoiseModel, contact_id: str,
) -> EoContact:
    """
    A contact that corresponds to no vessel at all: a wave crest, a buoy, a wake, a
    channel marker misread by the detector as a hull.

    WHY THIS IS IN THE SCENE ON PURPOSE. Clutter is the dominant source of DARK false
    positives in any real deployment -- far more common than an actual dark vessel -- so
    a harness without it flatters the pipeline enormously. If the prioritizer cannot
    push clutter below a real anomaly, criterion 2 has not been met, and this is the only
    thing in the scene that tests that.
    """
    rel = float(rng.uniform(-pose.fov_half_angle_deg, pose.fov_half_angle_deg))
    bearing = wrap_360(pose.boresight_deg_true + rel)
    rng_m = float(rng.uniform(0.25, 1.0)) * pose.max_range_m
    centre_x = pixel_column_for_relative_bearing(rel, pose.image_width_px, pose.hfov_deg)
    w = float(rng.uniform(6.0, 22.0))
    h = max(3.0, w / 2.5)
    x0 = int(max(0, round(centre_x - w / 2)))
    x1 = int(min(pose.image_width_px, round(centre_x + w / 2)))
    y_c = pose.image_height_px * 0.56
    return EoContact(
        contact_id=contact_id,
        frame_time_utc=scene_time,
        frame_ref=f"synthetic://{pose.pose_ref}/{scene_time.isoformat()}",
        bbox_px=(x0, int(y_c - h / 2), max(x0 + 1, x1), int(y_c + h / 2)),
        observed_bearing_deg_true=bearing,
        bearing_uncertainty_deg=bearing_uncertainty_deg(
            float(max(1, x1 - x0)), float(centre_x), pose.image_width_px,
            pose.hfov_deg, pose.yaw_uncertainty_deg),
        detection_confidence=_synthetic_detection_confidence(w, rng),
        observed_bearing_rel_deg=rel,
        observed_range_m=rng_m,
        range_uncertainty_m=rng_m * noise.range_fraction_sigma or 1.0,
        observed_class=None,                 # the detector fired; the VLM could not say
        observed_class_confidence=None,
        observed_length_m=None,
        observed_length_uncertainty_m=None,
        track_length_frames=1,               # clutter does not persist -> defer signal
        camera_pose_ref=pose.pose_ref,
    )


# ============================================================================
# Mutation: turning truth into a lie.
# ============================================================================

def spoof_length(track: AisTrack, factor: float, *, keep_size_consistent: bool) -> AisTrack:
    """
    Rewrite the claimed length.

    THE SUBTLETY WORTH KNOWING: AIS declares dimensions TWICE -- once as Length/Width,
    and once as the reference-point offsets Size A/B/C/D, where A+B == length. A lazy
    spoofer changes only Length and leaves A+B contradicting it, which is detectable
    from the AIS message ALONE, without a camera at all. That is a real and cheap check
    and consistency.py should have it.

    keep_size_consistent=True generates the COMPETENT spoofer who updates both, and
    that one can only be caught by the camera. Default True, because building for the
    lazy adversary is how you get a demo that impresses nobody who knows the domain.
    """
    d = track.model_dump()
    old = d.get("claimed_length_m")
    if old is None:
        return track
    new = round(old * factor, 1)
    d["claimed_length_m"] = new
    if keep_size_consistent and d.get("claimed_size_a_m") is not None \
            and d.get("claimed_size_b_m") is not None:
        ratio = new / old if old else 1.0
        d["claimed_size_a_m"] = round(d["claimed_size_a_m"] * ratio, 1)
        d["claimed_size_b_m"] = round(d["claimed_size_b_m"] * ratio, 1)
    return AisTrack(**d)


def spoof_class(track: AisTrack, new_class: str) -> AisTrack:
    d = track.model_dump()
    d["claimed_ship_type"] = new_class
    return AisTrack(**d)


def spoof_position(track: AisTrack, offset_m: float, azimuth_deg: float) -> AisTrack:
    """
    Displace the CLAIM, leaving the hull where it is.

    This is the one spoof where the observation is untouched: the vessel is physically
    where it always was, and the camera sees it there. The lie is only in the broadcast.
    Downstream this shows up twice -- as an in-view claim with nothing at its position,
    and as an observation whose nearest claim is 800 m away -- which is why association
    reports BOTH an unmatched track and an unmatched contact, and why verdict.py has to
    be careful not to count one event as two findings.
    """
    d = track.model_dump()
    lon2, lat2, _ = GEOD.fwd(d["claimed_lon_deg"], d["claimed_lat_deg"],
                             azimuth_deg, offset_m)
    d["claimed_lat_deg"] = float(lat2)
    d["claimed_lon_deg"] = float(lon2)
    return AisTrack(**d)


def spoof_heading(track: AisTrack, delta_deg: float) -> AisTrack:
    d = track.model_dump()
    base = d.get("claimed_heading_deg_true")
    if base is None:
        base = d.get("claimed_cog_deg_true")
    if base is None:
        return track
    d["claimed_heading_deg_true"] = wrap_360(base + delta_deg)
    return AisTrack(**d)


# ============================================================================
# Scene assembly.
# ============================================================================

def build_scene(
    *, tracks: list[AisTrack], pose: ScenePose, scene_time: datetime,
    rng: np.random.Generator, noise: NoiseModel, plan: dict[str, int],
    keep_size_consistent: bool,
) -> dict[str, Any]:
    proj = project(tracks, pose)
    visible_idx = [i for i, v in enumerate(proj["visible"]) if v]
    hidden_idx = [i for i, v in enumerate(proj["visible"]) if not v]

    if not visible_idx:
        raise SystemExit(
            "No vessel is inside the camera field of view. The pose and the traffic "
            "disagree. Re-run with --auto-pose, or widen --hfov / --max-range."
        )

    # Choose victims WITHOUT replacement so one vessel never carries two faults --
    # a hull that is both dark and spoofed is not a scenario, it is a bug generator.
    rng.shuffle(visible_idx)
    rng.shuffle(hidden_idx)
    vis_pool, hid_pool = list(visible_idx), list(hidden_idx)
    assigned: dict[int, str] = {}
    injections: list[Injection] = []

    def take(pool: list[int], kind: str) -> int | None:
        while pool:
            i = pool.pop()
            if i not in assigned:
                assigned[i] = kind
                return i
        return None

    for kind in ("dark", "length_spoof", "class_spoof", "position_spoof",
                 "heading_spoof", "missed_detection"):
        for _ in range(plan.get(kind, 0)):
            i = take(vis_pool, kind)
            if i is None:
                print(f"WARNING: not enough visible vessels for another {kind}",
                      file=sys.stderr)
                break
    for _ in range(plan.get("coverage_hole", 0)):
        i = take(hid_pool, "coverage_hole")
        if i is None:
            print("WARNING: no out-of-view vessel available for a coverage_hole "
                  "control. The false-positive measurement is weaker without it.",
                  file=sys.stderr)
            break

    out_tracks: list[AisTrack] = []
    out_contacts: list[EoContact] = []

    for i, track in enumerate(tracks):
        kind = assigned.get(i)
        visible = bool(proj["visible"][i])
        bearing = float(proj["bearing"][i])
        range_m = float(proj["range"][i])
        cid = f"c-{i:04d}"
        n_frames = int(rng.integers(3, 30))

        emit_contact = visible
        emit_track = True
        mutated = track
        detail: dict[str, Any] = {}

        if kind == "dark":
            emit_track = False
        elif kind == "missed_detection":
            emit_contact = False
        elif kind == "coverage_hole":
            emit_track = False
        elif kind == "length_spoof":
            factor = float(rng.choice([0.25, 0.3, 3.5, 5.0]))
            mutated = spoof_length(track, factor,
                                   keep_size_consistent=keep_size_consistent)
            detail = {"factor": factor,
                      "claimed_length_m_before": track.claimed_length_m,
                      "claimed_length_m_after": mutated.claimed_length_m,
                      "size_fields_kept_consistent": keep_size_consistent}
        elif kind == "class_spoof":
            options = [c for c in ("cargo", "tanker", "fishing", "passenger", "tug")
                       if c != track.claimed_ship_type]
            new_class = str(rng.choice(options))
            mutated = spoof_class(track, new_class)
            detail = {"claimed_ship_type_before": track.claimed_ship_type,
                      "claimed_ship_type_after": new_class}
        elif kind == "position_spoof":
            offset = float(rng.uniform(600.0, 1500.0))
            az = float(rng.uniform(0.0, 360.0))
            mutated = spoof_position(track, offset, az)
            detail = {"offset_m": round(offset, 1), "azimuth_deg": round(az, 1)}
        elif kind == "heading_spoof":
            delta = float(rng.choice([-140.0, -110.0, 110.0, 140.0]))
            mutated = spoof_heading(track, delta)
            detail = {"delta_deg": delta}

        # Untargeted missed detections, on top of the deliberate one.
        if emit_contact and kind is None and rng.random() < noise.p_missed_detection:
            emit_contact = False
            detail = {"reason": "random missed detection from the noise model"}
            kind_for_gt = None
        else:
            kind_for_gt = kind

        if emit_track:
            out_tracks.append(mutated)
        if emit_contact:
            out_contacts.append(make_contact(
                track=track, bearing_true=bearing, range_m=range_m, pose=pose,
                scene_time=scene_time, rng=rng, noise=noise, contact_id=cid,
                track_length_frames=n_frames))

        if kind_for_gt:
            label, subtype, must_not = EXPECTATIONS[kind_for_gt]
            injections.append(Injection(
                kind=kind_for_gt, mmsi=track.claimed_mmsi,
                track_id=mutated.track_id if emit_track else None,
                contact_id=cid if emit_contact else None,
                detail=detail, expected_label=label,
                expected_spoof_subtype=subtype, must_not_fire=must_not))

    for k in range(noise.n_clutter_contacts):
        cid = f"clutter-{k:03d}"
        out_contacts.append(make_clutter_contact(
            pose=pose, scene_time=scene_time, rng=rng, noise=noise, contact_id=cid))
        injections.append(Injection(
            kind="clutter", mmsi="-", contact_id=cid,
            detail={"note": "no vessel exists here"},
            expected_label="UNKNOWN", must_not_fire=True))

    return {"tracks": out_tracks, "contacts": out_contacts,
            "injections": injections, "projection": proj,
            "n_visible": len(visible_idx), "n_hidden": len(hidden_idx)}


# ============================================================================
# Output.
# ============================================================================

def write_scene(out_dir: Path, scene: dict[str, Any], manifest: dict[str, Any]) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    def dump(name: str, rows: Iterable[Any]) -> int:
        p = out_dir / name
        n = 0
        with p.open("w", encoding="utf-8") as fh:
            for r in rows:
                obj = r.model_dump(mode="json") if hasattr(r, "model_dump") else r
                fh.write(json.dumps(obj, ensure_ascii=False) + "\n")
                n += 1
        return n

    n_t = dump("ais_tracks.jsonl", scene["tracks"])
    n_c = dump("eo_contacts.jsonl", scene["contacts"])
    n_g = dump("ground_truth.jsonl", [i.to_dict() for i in scene["injections"]])

    manifest["counts"] = {"ais_tracks": n_t, "eo_contacts": n_c,
                          "injections": n_g}
    (out_dir / "scene_manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")

    # A deliberate tripwire. If this file is ever missing, someone has copied the
    # scene somewhere and dropped the caveat with it.
    (out_dir / "READ_ME_FIRST.txt").write_text(
        "SYNTHETIC ELECTRO-OPTICAL DATA. NOT A CAMERA.\n\n"
        "The AIS in this scene is real Danish Maritime Authority traffic, pseudonymised.\n"
        "The EO contacts were forward-projected from that AIS through a declared camera\n"
        "pose and perturbed with a measurement-error model. No camera observed anything.\n"
        "Anomalies were injected deliberately; ground_truth.jsonl is the answer key.\n\n"
        "Any figure derived from this scene -- detection rate, false-positive rate,\n"
        "confidence -- describes the pipeline against a MODEL of a camera, never against\n"
        "the sea. Say so on the slide.\n", encoding="utf-8")


def print_summary(scene: dict[str, Any], pose: ScenePose, manifest: dict[str, Any]) -> None:
    """Self-interpreting output: every line says what it means, so it can be pasted
    into STATUS.md without a second round trip."""
    print()
    print("=" * 74)
    print("SYNTHETIC SCENE BUILT -- D0 replay harness")
    print("=" * 74)
    print(f"pose            : {pose.pose_ref}")
    print(f"  camera at     : {pose.lat_deg:.5f} N, {pose.lon_deg:.5f} E")
    print(f"  boresight     : {pose.boresight_deg_true:.2f} deg TRUE, "
          f"HFOV {pose.hfov_deg:.1f} deg, max range {pose.max_range_m/1000:.1f} km")
    print(f"  yaw sigma     : {pose.yaw_uncertainty_deg:.2f} deg  <- floors every "
          f"bearing uncertainty in the run")
    print(f"vessels loaded  : {manifest['ais']['vessels']}")
    print(f"  in view       : {scene['n_visible']}   out of view: {scene['n_hidden']}")
    print(f"emitted         : {len(scene['tracks'])} AisTrack, "
          f"{len(scene['contacts'])} EoContact")
    print()
    print("INJECTED (ground_truth.jsonl is the answer key):")
    by_kind: dict[str, int] = {}
    for inj in scene["injections"]:
        by_kind[inj.kind] = by_kind.get(inj.kind, 0) + 1
    for kind in sorted(by_kind):
        exp = EXPECTATIONS.get(kind, ("UNKNOWN", None, True))
        flag = "  MUST NOT FIRE -- false-positive control" if exp[2] else ""
        print(f"  {kind:<18} x{by_kind[kind]:<3} expect {exp[0]:<8}{flag}")
    print()
    print("The two controls are the point. Anything can raise an alert; the measured")
    print("false-positive rate comes from how often those rows stay silent.")
    print("=" * 74)


# ============================================================================
# CLI.
# ============================================================================

def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Build a synthetic EO scene from real AIS. Indoor demo, D0.")
    p.add_argument("--ais", required=True, type=Path,
                   help="Pseudonymised golden-window CSV (*_anon.csv).")
    p.add_argument("--out", required=True, type=Path, help="Output directory.")
    p.add_argument("--scene-time", type=str, default=None,
                   help="ISO-8601 with offset. Default: midpoint of the AIS window.")
    p.add_argument("--window-s", type=float, default=120.0,
                   help="Half-width, seconds, for picking each vessel's truth state.")
    p.add_argument("--seed", type=int, default=20260830,
                   help="Recorded in the manifest. Same seed = same scene.")

    g = p.add_argument_group("camera pose")
    g.add_argument("--auto-pose", action="store_true", default=True,
                   help="Place the camera across the busiest lane. Default.")
    g.add_argument("--camera-lat", type=float)
    g.add_argument("--camera-lon", type=float)
    g.add_argument("--boresight", type=float, help="Degrees TRUE.")
    g.add_argument("--hfov", type=float, default=60.0)
    g.add_argument("--yaw-sigma", type=float, default=2.0,
                   help="1-sigma pose yaw error. 1.0 surveyed, 5.0 phone compass, "
                        "180.0 = deliberately worthless.")
    g.add_argument("--max-range", type=float, default=8000.0)
    g.add_argument("--image-width", type=int, default=1920)
    g.add_argument("--image-height", type=int, default=1080)

    f = p.add_argument_group("fault injection")
    for kind, default in (("dark", 2), ("length-spoof", 2), ("class-spoof", 1),
                          ("position-spoof", 1), ("heading-spoof", 1),
                          ("coverage-hole", 2), ("missed-detection", 1)):
        f.add_argument(f"--n-{kind}", type=int, default=default)
    f.add_argument("--lazy-spoofer", action="store_true",
                   help="Length spoof leaves Size A/B contradicting Length, which is "
                        "detectable from AIS alone. Default is the competent spoofer.")
    f.add_argument("--noise", choices=("normal", "none"), default="normal",
                   help="'none' is for debugging plumbing ONLY. A zero-noise scene "
                        "associates at zero sigma and proves nothing.")
    f.add_argument("--allow-real-identities", action="store_true",
                   help="Dangerous. Permits non-999 MMSIs. Output must never be shown.")
    p.add_argument("--dry-run", action="store_true",
                   help="Print the scene summary, write nothing.")
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)

    if not args.ais.exists():
        raise SystemExit(
            f"AIS file not found: {args.ais}\n"
            "Run 02_data/make_golden_window.py first, and point --ais at the "
            "*_anon.csv it writes.")

    if args.scene_time:
        scene_time = datetime.fromisoformat(args.scene_time)
        if scene_time.tzinfo is None:
            raise SystemExit(
                "--scene-time has no UTC offset. Naive datetimes are refused here for "
                "the same reason contracts.py refuses them: the DMA CSV is dd/mm/yyyy "
                "and a silently-assumed timezone is how a two-hour error reaches a "
                "verdict.")
    else:
        scene_time = datetime(2026, 8, 25, 10, 30, tzinfo=timezone.utc)

    tracks, ais_stats = load_truth_states(args.ais, scene_time, args.window_s)
    if not tracks:
        raise SystemExit(
            f"No AIS reports within +/-{args.window_s:.0f}s of {scene_time.isoformat()}. "
            "Check --scene-time against the window in the file name.")
    assert_pseudonymised(tracks, allow_real=args.allow_real_identities)

    if args.camera_lat is not None and args.camera_lon is not None \
            and args.boresight is not None:
        pose = ScenePose(
            pose_ref="synthetic-manual", lat_deg=args.camera_lat,
            lon_deg=args.camera_lon, boresight_deg_true=wrap_360(args.boresight),
            hfov_deg=args.hfov, yaw_uncertainty_deg=args.yaw_sigma,
            max_range_m=args.max_range, image_width_px=args.image_width,
            image_height_px=args.image_height, height_m=25.0)
    else:
        pose = auto_pose(tracks, max_range_m=args.max_range, hfov_deg=args.hfov,
                         yaw_uncertainty_deg=args.yaw_sigma,
                         image_width_px=args.image_width,
                         image_height_px=args.image_height)

    noise = NoiseModel() if args.noise == "normal" else NoiseModel.off()
    rng = np.random.default_rng(args.seed)
    plan = {
        "dark": args.n_dark, "length_spoof": args.n_length_spoof,
        "class_spoof": args.n_class_spoof, "position_spoof": args.n_position_spoof,
        "heading_spoof": args.n_heading_spoof, "coverage_hole": args.n_coverage_hole,
        "missed_detection": args.n_missed_detection,
    }

    scene = build_scene(tracks=tracks, pose=pose, scene_time=scene_time, rng=rng,
                        noise=noise, plan=plan,
                        keep_size_consistent=not args.lazy_spoofer)

    manifest = {
        "harness_version": HARNESS_VERSION,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "seed": args.seed,
        "geometry_source": _GEOM_SOURCE,
        "ais": {"path": str(args.ais), **ais_stats},
        "pose": pose.to_dict(),
        "noise_model": {k: getattr(noise, k) for k in noise.__dataclass_fields__},
        "fault_plan": plan,
        "spoofer_competence": "lazy" if args.lazy_spoofer else "competent",
        "caveats": [
            "EO contacts are SYNTHETIC. No camera observed anything.",
            "AIS is real DMA traffic, pseudonymised to 999-prefixed MMSIs.",
            "Noise-model parameters are defensible estimates, NOT measurements.",
            "Pose yaw error is applied per-contact; in reality it is systematic "
            "across a run and rotates the whole scene together.",
            "Observed length and observed range are perturbed independently; in "
            "reality length is derived from range and the two errors are correlated.",
            "No sea clutter, weather, glare, occlusion by other hulls, or lens "
            "distortion is modelled beyond the clutter contacts listed above.",
        ],
    }

    print_summary(scene, pose, manifest)
    if args.dry_run:
        print("\n--dry-run: nothing written.")
        return 0

    write_scene(args.out, scene, manifest)
    print(f"\nwritten to {args.out}/")
    for f_ in ("ais_tracks.jsonl", "eo_contacts.jsonl", "ground_truth.jsonl",
               "scene_manifest.json", "READ_ME_FIRST.txt"):
        print(f"  {f_}")
    print("\nNothing in 03_src may import ground_truth.jsonl. It is the answer key.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
